sonar.projectKey=JorgeALaRosaG_AppFirstAngularS6
sonar.organizationKey=jorgealarosag
sonar.projectName=AppFirstAngularS6
sonar.projectVersion=0.0.0
sonar.host.url=http://localhost:9000

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,.angular/**,coverage/**,src/**/*.spec.ts

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/app-first-angular/lcov.info
